services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fileupload
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fileupload
      AWS_ACCESS_KEY_ID: AKIARYEUCNABWGGXSEX2
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: eu-central-1
    command: ["sh", "-c", "npm run dev"]

volumes:
  db_data:
